# Generated by Django 4.2 on 2025-10-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('dry', 'Dry Sweet'), ('syrupy', 'Syrupy Sweet'), ('festive', 'Festive Special')], max_length=20)),
                ('image', models.ImageField(upload_to='sweet_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.sweet')),
            ],
        ),
    ]
