# Generated by Django 4.2 on 2025-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(choices=[('Milk', 'Milk Sweets'), ('DryFruit', 'Dry Fruit Sweets'), ('Ghee', 'Ghee Sweets'), ('Ragi', 'Ragi Sweets'), ('BurfiHalwa', 'Burfi & Halwa'), ('SugarFree', 'Sugar-Free Sweets')], max_length=20),
        ),
    ]
