# Generated by Django 4.2 on 2025-10-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_sweet_is_best_seller_alter_sweet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(choices=[('milk', 'Milk Sweets'), ('dryfruit', 'Dry Fruit Sweets'), ('ghee', 'Ghee Sweets'), ('ragi', 'Ragi Sweets'), ('burfihalwa', 'Burfi & Halwa'), ('sugarfree', 'Sugar-Free Sweets')], max_length=20),
        ),
    ]
