# Generated by Django 4.2 on 2025-11-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_ordered_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sweet_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.sweet'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_gm',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='sweet',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to feature on homepage'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(blank=True, choices=[('dryfruit', 'Dry Fruit Sweets'), ('milk', 'Milk Sweets'), ('ghee', 'Ghee Sweets'), ('ragi', 'Ragi Sweets'), ('burfi_halwa', 'Burfi & Halwa'), ('sugarfree', 'Sugar Free')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='image',
            field=models.ImageField(upload_to='sweets/'),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Check this for best-seller carousel'),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
